[package]
name = "rua-jit"
version = "0.1.0"
edition = "2021"

[dependencies]
iced-x86 = { version = "1.21.0", features = ["code_asm"] }
ast = { path = "../ast" }
windows = { version = "0.58.0", features = ["Win32", "Win32_System", "Win32_System_Memory"] }
